# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/danilmalyshev/Desktop/MyProgect/Chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/danilmalyshev/Desktop/MyProgect/Chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danilmalyshev/Desktop/MyProgect/Chess/CMakeFiles /Users/danilmalyshev/Desktop/MyProgect/Chess//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danilmalyshev/Desktop/MyProgect/Chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Chess

# Build rule for target.
Chess: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Chess
.PHONY : Chess

# fast build rule for target.
Chess/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/build
.PHONY : Chess/fast

src/Figures/Figure.o: src/Figures/Figure.cpp.o
.PHONY : src/Figures/Figure.o

# target to build an object file
src/Figures/Figure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Figures/Figure.cpp.o
.PHONY : src/Figures/Figure.cpp.o

src/Figures/Figure.i: src/Figures/Figure.cpp.i
.PHONY : src/Figures/Figure.i

# target to preprocess a source file
src/Figures/Figure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Figures/Figure.cpp.i
.PHONY : src/Figures/Figure.cpp.i

src/Figures/Figure.s: src/Figures/Figure.cpp.s
.PHONY : src/Figures/Figure.s

# target to generate assembly for a file
src/Figures/Figure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Figures/Figure.cpp.s
.PHONY : src/Figures/Figure.cpp.s

src/Logic.o: src/Logic.cpp.o
.PHONY : src/Logic.o

# target to build an object file
src/Logic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Logic.cpp.o
.PHONY : src/Logic.cpp.o

src/Logic.i: src/Logic.cpp.i
.PHONY : src/Logic.i

# target to preprocess a source file
src/Logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Logic.cpp.i
.PHONY : src/Logic.cpp.i

src/Logic.s: src/Logic.cpp.s
.PHONY : src/Logic.s

# target to generate assembly for a file
src/Logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Logic.cpp.s
.PHONY : src/Logic.cpp.s

src/Windows/MainMenu.o: src/Windows/MainMenu.cpp.o
.PHONY : src/Windows/MainMenu.o

# target to build an object file
src/Windows/MainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/MainMenu.cpp.o
.PHONY : src/Windows/MainMenu.cpp.o

src/Windows/MainMenu.i: src/Windows/MainMenu.cpp.i
.PHONY : src/Windows/MainMenu.i

# target to preprocess a source file
src/Windows/MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/MainMenu.cpp.i
.PHONY : src/Windows/MainMenu.cpp.i

src/Windows/MainMenu.s: src/Windows/MainMenu.cpp.s
.PHONY : src/Windows/MainMenu.s

# target to generate assembly for a file
src/Windows/MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/MainMenu.cpp.s
.PHONY : src/Windows/MainMenu.cpp.s

src/Windows/PlayMenu.o: src/Windows/PlayMenu.cpp.o
.PHONY : src/Windows/PlayMenu.o

# target to build an object file
src/Windows/PlayMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/PlayMenu.cpp.o
.PHONY : src/Windows/PlayMenu.cpp.o

src/Windows/PlayMenu.i: src/Windows/PlayMenu.cpp.i
.PHONY : src/Windows/PlayMenu.i

# target to preprocess a source file
src/Windows/PlayMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/PlayMenu.cpp.i
.PHONY : src/Windows/PlayMenu.cpp.i

src/Windows/PlayMenu.s: src/Windows/PlayMenu.cpp.s
.PHONY : src/Windows/PlayMenu.s

# target to generate assembly for a file
src/Windows/PlayMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/PlayMenu.cpp.s
.PHONY : src/Windows/PlayMenu.cpp.s

src/Windows/Setting.o: src/Windows/Setting.cpp.o
.PHONY : src/Windows/Setting.o

# target to build an object file
src/Windows/Setting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/Setting.cpp.o
.PHONY : src/Windows/Setting.cpp.o

src/Windows/Setting.i: src/Windows/Setting.cpp.i
.PHONY : src/Windows/Setting.i

# target to preprocess a source file
src/Windows/Setting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/Setting.cpp.i
.PHONY : src/Windows/Setting.cpp.i

src/Windows/Setting.s: src/Windows/Setting.cpp.s
.PHONY : src/Windows/Setting.s

# target to generate assembly for a file
src/Windows/Setting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/Setting.cpp.s
.PHONY : src/Windows/Setting.cpp.s

src/Windows/TypeGame.o: src/Windows/TypeGame.cpp.o
.PHONY : src/Windows/TypeGame.o

# target to build an object file
src/Windows/TypeGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/TypeGame.cpp.o
.PHONY : src/Windows/TypeGame.cpp.o

src/Windows/TypeGame.i: src/Windows/TypeGame.cpp.i
.PHONY : src/Windows/TypeGame.i

# target to preprocess a source file
src/Windows/TypeGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/TypeGame.cpp.i
.PHONY : src/Windows/TypeGame.cpp.i

src/Windows/TypeGame.s: src/Windows/TypeGame.cpp.s
.PHONY : src/Windows/TypeGame.s

# target to generate assembly for a file
src/Windows/TypeGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/Windows/TypeGame.cpp.s
.PHONY : src/Windows/TypeGame.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Chess.dir/build.make CMakeFiles/Chess.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Chess"
	@echo "... src/Figures/Figure.o"
	@echo "... src/Figures/Figure.i"
	@echo "... src/Figures/Figure.s"
	@echo "... src/Logic.o"
	@echo "... src/Logic.i"
	@echo "... src/Logic.s"
	@echo "... src/Windows/MainMenu.o"
	@echo "... src/Windows/MainMenu.i"
	@echo "... src/Windows/MainMenu.s"
	@echo "... src/Windows/PlayMenu.o"
	@echo "... src/Windows/PlayMenu.i"
	@echo "... src/Windows/PlayMenu.s"
	@echo "... src/Windows/Setting.o"
	@echo "... src/Windows/Setting.i"
	@echo "... src/Windows/Setting.s"
	@echo "... src/Windows/TypeGame.o"
	@echo "... src/Windows/TypeGame.i"
	@echo "... src/Windows/TypeGame.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

